### PR TITLE
fix: support pull request title with directory path

### PR DESCRIPTION
**Pull request by pankona**
It seems currently Merge me doesn't respect PRESET parameter if the pull request's title includes directory path, like:
`Bump @types/jest from 14.14.41 to 16.4.0 in /directory`.
For example, this causes merge me to merge a pull request that bumps the major version even if DEPENDABOT_PATCH is specified to PRESET.

This commit fixes regexp for parsing versions in the pull request title.

### CODE REVIEW

**Comment by pankona** [comment]
Hi, great oss owner!

Here's my first contribution. If it is something wrong, please let me know.
Thanks in advance! 💪

**Comment by pankona** [comment]
Gently pinging 🏓

**Comment by mjroeleveld** [comment]
@pankona excuse me for the delay. Thank you for this contribution!

**Review by mjroeleveld — APPROVED** [review]

**Comment by pankona** [comment]
@mjroeleveld 

Thank you!! 😋

**Pull request merged**
