### PR TITLE
fix: make PR title semver regex case-insensitive

### PR DESCRIPTION
**Pull request by ColeKettler**
Prevent allowing major version bumps when PRESET is present and PR title is capitalized, e.g. "Bump"
instead of "bump."

Bug has been reproduced in https://github.com/ColeKettler/merge-me-action-preset-bug/pull/1, where `PRESET` is set to `DEPENDABOT_MINOR` in [workflow file](https://github.com/ColeKettler/merge-me-action-preset-bug/blob/main/.github/workflows/merge-dependabot.yml#L26).

This Pull Request fulfills the following requirements:

- [x] The commit message follows our guidelines.
- [x] Tests for the changes have been added if needed.
- [x] Does not affect documentation or it has been added or updated.

### CODE REVIEW

**Comment by ColeKettler** [comment]
It looks like the `Merge me!` step failed due to secrets not being available in forks. I'm not sure if that's something I'll be able to fix on my end.

By the way, thanks for setting up this project! It's exactly what we needed to really get into using Dependabot for our projects. 💖

**Comment by dunyakirkali** [comment]
Thnx for the PR @ColeKettler 
I'll look at it tomorrow

**Review by dunyakirkali — APPROVED** [review]
LGTM

**Comment by dunyakirkali** [comment]
@viestat I can't seem to figure out why the merge-me step is failing. Any clues?

**Review by viestat — APPROVED** [review]

**Comment by viestat** [comment]
@dunyakirkali it is as @ColeKettler said, the secrets are not available to forks. It should be fine once it is merged.
In order to fix it (which I don't think is necessary), @ColeKettler should add a `GITHUB_TOKEN` secret to their fork, matching the name used in the CI workflow definition (`DOTTBOTT_TOKEN`).

**Comment by dunyakirkali** [comment]
@viestat shall we merge this PR then?

**Comment by ColeKettler** [comment]
Good to know that I could have set that on my end to get past that error. I appreciate y'all's hard work on this, thank you again!

**Pull request merged**
